import type { EbayApiClient, EbayRequestConfig } from '@/api/client.js';
import {
  type DownloadedFile,
  type DownloadTooLargeError,
  requestDownloadEffect,
} from '@/api/shared/download.js';
import { type LocatedResource, locatedResourceId } from '@/api/shared/location.js';
import {
  buildEndpointParams,
  EbayApiError,
  EndpointInputError,
  type QueryParams,
} from '@/api/shared/request.js';
import { decodeEffectSchema } from '@/utils/effectSchema.js';
import type { EffectBackedSchema, InferEffectSchema } from '@/utils/effectSchemaTypes.js';
import { Effect } from 'effect';

/** Feed API base path on the default `api` host. */
export const FEED_BASE_PATH = '/sell/feed/v1';

/** Query parameters shared by the Feed API list endpoints; each endpoint's schema allows a subset. */
export interface FeedListQuery {
  /** `feed_type`: the feed type to list. */
  readonly feedType?: string;
  /** `schedule_id`: tasks generated by one schedule. */
  readonly scheduleId?: string;
  /** `date_range`: task creation window, `from..to` in UTC. */
  readonly dateRange?: string;
  /** `look_back_days`: task creation window counted back from today. */
  readonly lookBackDays?: number;
  /** `limit`: page size. */
  readonly limit?: number;
  /** `offset`: results to skip. */
  readonly offset?: number;
}

/** Feed task created asynchronously; eBay reports its ID only in the `Location` header. */
export interface CreatedFeedTask {
  /** Task ID decoded from the `Location` header. */
  readonly taskId: string;
  /** `Location` header exactly as eBay returned it. */
  readonly location: string;
}

/**
 * Decodes endpoint input through its Effect-backed schema before any request is sent.
 *
 * @param schema - Endpoint input schema from `@/schemas/inventory-management/feed.js`.
 * @param input - Caller-supplied input.
 * @returns An Effect with the decoded input, or an EndpointInputError.
 * @example decodeFeedInput(feedTaskIdInputSchema, { taskId: 'TASK-1' })
 */
export const decodeFeedInput = <TSchema extends EffectBackedSchema>(
  schema: TSchema,
  input: unknown,
): Effect.Effect<InferEffectSchema<TSchema>, EndpointInputError> =>
  decodeEffectSchema(schema, input).pipe(
    Effect.mapError(
      (cause) => new EndpointInputError({ parameter: 'input', message: cause.message }),
    ),
  );

/**
 * Feed API path of one resource, with its ID encoded as a single path segment.
 *
 * @param collection - Collection path below the base path, e.g. `/task`.
 * @param id - Resource ID.
 * @param suffix - Optional sub-path, e.g. `/download_result_file`.
 * @returns The full REST path.
 * @example feedResourcePath('/task', 'TASK-1', '/upload_file')
 */
export const feedResourcePath = (collection: string, id: string, suffix = ''): string =>
  `${FEED_BASE_PATH}${collection}/${encodeURIComponent(id)}${suffix}`;

/**
 * Builds the query of a Feed API list endpoint with eBay's wire names.
 *
 * @param query - Decoded list filters and pagination.
 * @returns Query params, or undefined when every value is omitted.
 * @example feedListParams({ feedType: 'LMS_ORDER_REPORT', limit: 10 })
 */
export const feedListParams = (query: FeedListQuery): QueryParams | undefined =>
  buildEndpointParams({
    feedType: { wireName: 'feed_type', value: query.feedType },
    scheduleId: { wireName: 'schedule_id', value: query.scheduleId },
    dateRange: { wireName: 'date_range', value: query.dateRange },
    lookBackDays: { wireName: 'look_back_days', value: query.lookBackDays },
    limit: { wireName: 'limit', value: query.limit },
    offset: { wireName: 'offset', value: query.offset },
  });

/**
 * POSTs a Feed API create request whose new resource ID arrives only in `Location`.
 *
 * @param client - Shared authenticated HTTP client.
 * @param collection - Collection path below the base path, e.g. `/schedule`.
 * @param body - Generated create-request DTO.
 * @param config - Optional per-request headers.
 * @returns An Effect with the decoded ID and Location, or an EbayApiError.
 * @example postFeedResource(client, '/schedule', { feedType: 'LMS_ORDER_REPORT', scheduleTemplateId: 'T-1' })
 */
export const postFeedResource = (
  client: EbayApiClient,
  collection: string,
  body: unknown,
  config?: EbayRequestConfig,
): Effect.Effect<LocatedResource, EbayApiError> => {
  const path = `${FEED_BASE_PATH}${collection}`;
  return Effect.tryPromise({
    try: () => client.postForResponse<unknown>(path, body, config),
    catch: (cause) => new EbayApiError({ method: 'POST', path, cause }), // allow-duplicate
  }).pipe(Effect.flatMap((response) => locatedResourceId(response.headers.location, path)));
};

/**
 * Creates a Feed API task (HTTP 202, no body) and returns the ID from its `Location`.
 *
 * @param client - Shared authenticated HTTP client.
 * @param collection - Task collection path, e.g. `/order_task`.
 * @param body - Generated create-task DTO.
 * @param headers - Optional request headers such as Accept-Language.
 * @returns An Effect with the new task ID and Location, or an EbayApiError.
 * @example postFeedTask(client, '/task', { feedType: 'LMS_ORDER_ACK', schemaVersion: '1235' })
 */
export const postFeedTask = (
  client: EbayApiClient,
  collection: string,
  body: unknown,
  headers?: Record<string, string>,
): Effect.Effect<CreatedFeedTask, EbayApiError> =>
  postFeedResource(client, collection, body, headers ? { headers } : undefined).pipe(
    Effect.map(({ id, location }) => ({ taskId: id, location })),
  );

/**
 * Downloads a Feed API file (input, result or latest schedule report) as raw bytes.
 *
 * @param client - Shared authenticated HTTP client.
 * @param path - Full Feed API download path.
 * @returns An Effect with the bytes, content type and file name.
 * @example downloadFeedFile(client, feedResourcePath('/task', 'TASK-1', '/download_result_file'))
 */
export const downloadFeedFile = (
  client: EbayApiClient,
  path: string,
): Effect.Effect<DownloadedFile, EbayApiError | DownloadTooLargeError> =>
  requestDownloadEffect(client, path, { headers: { Accept: 'application/octet-stream' } });
