import { z } from 'zod';

const nonempty = z.string().min(1).regex(/\S/, 'Must contain a non-whitespace character');
const taskId = nonempty.describe('Feed task ID, from the Location of a create call or a task list');
const scheduleId = nonempty.describe('Feed schedule ID, from ebay_create_feed_schedule or a list');
const scheduleIdFilter = nonempty
  .optional()
  .describe('Only tasks generated by this schedule; do not combine with feedType');
const dateRange = nonempty
  .optional()
  .describe(
    'Task creation window in UTC, e.g. 2026-09-01T00:00:00.000Z..2026-09-08T00:00:00.000Z (at most 90 days); do not combine with lookBackDays',
  );
const lookBackDays = z
  .number()
  .int()
  .min(1)
  .max(90)
  .optional()
  .describe(
    'Search tasks created in the last 1-90 days (eBay default 7); do not combine with dateRange',
  );
const limit = z
  .number()
  .int()
  .min(1)
  .max(500)
  .optional()
  .describe('Page size, 1-500 (eBay default 10)');
const offset = z
  .number()
  .int()
  .min(0)
  .optional()
  .describe('Zero-based number of results to skip (default 0)');
const acceptLanguage = nonempty
  .optional()
  .describe('Accept-Language header, e.g. en-US; defaults to EBAY_CONTENT_LANGUAGE (en-US)');
const dateWindow = z.object({
  from: nonempty.optional().describe('Start, UTC yyyy-MM-ddThh:mm:ss.SSSZ'),
  to: nonempty.optional().describe('Inclusive end, UTC yyyy-MM-ddThh:mm:ss.SSSZ'),
});
const scheduleFields = {
  scheduleName: nonempty.optional().describe('Seller-assigned schedule name'),
  preferredTriggerHour: nonempty
    .optional()
    .describe('Two-digit UTC trigger hour, 00Z-23Z, e.g. 11Z; available as the template allows'),
  preferredTriggerDayOfWeek: nonempty
    .optional()
    .describe(
      'DayOfWeekEnum for weekly schedules: MONDAY ... SUNDAY; available as the template allows',
    ),
  preferredTriggerDayOfMonth: z
    .number()
    .int()
    .min(1)
    .max(31)
    .optional()
    .describe(
      'Day of month, 1-31, for monthly schedules; days past the end of the month use the last day',
    ),
  scheduleStartDate: nonempty
    .optional()
    .describe('UTC start timestamp, yyyy-MM-ddTHH:00:00.000Z; available as the template allows'),
  scheduleEndDate: nonempty
    .optional()
    .describe('UTC end timestamp after scheduleStartDate; the schedule then becomes INACTIVE'),
  schemaVersion: nonempty
    .optional()
    .describe('Schema version of the report, when the template requires it'),
};

/** Feed task identifier for the task, order task, inventory task and service metric task resources. */
export const feedTaskIdInputSchema = z.object({ taskId });
/** Feed schedule identifier. */
export const feedScheduleIdInputSchema = z.object({ scheduleId });
/** Schedule template identifier. */
export const feedScheduleTemplateIdInputSchema = z.object({
  scheduleTemplateId: nonempty.describe(
    'Schedule template ID from ebay_get_feed_schedule_templates',
  ),
});

/** Filters for getOrderTasks. */
export const getOrderTasksInputSchema = z.object({
  feedType: nonempty
    .optional()
    .describe('LMS_ORDER_REPORT (the only supported value); do not combine with scheduleId'),
  scheduleId: scheduleIdFilter,
  dateRange,
  lookBackDays,
  limit,
  offset,
});
/** Filters for getInventoryTasks. */
export const getInventoryTasksInputSchema = z.object({
  feedType: nonempty.optional().describe('LMS_ACTIVE_INVENTORY_REPORT (the only supported value)'),
  scheduleId: nonempty
    .optional()
    .describe('Reserved: eBay does not offer schedules for ActiveInventoryReport yet'),
  dateRange,
  lookBackDays,
  limit,
  offset,
});
/** Filters for getTasks. */
export const getFeedTasksInputSchema = z.object({
  feedType: nonempty
    .optional()
    .describe(
      'Feed type, e.g. LMS_ORDER_REPORT, LMS_ORDER_ACK, LMS_ADD_FIXED_PRICE_ITEM or a Seller Hub feed type; do not combine with scheduleId',
    ),
  scheduleId: scheduleIdFilter,
  dateRange,
  lookBackDays,
  limit,
  offset,
});
/** Filters for getCustomerServiceMetricTasks. */
export const getCustomerServiceMetricTasksInputSchema = z.object({
  feedType: nonempty
    .optional()
    .describe('CUSTOMER_SERVICE_METRICS_REPORT (the only supported value)'),
  dateRange,
  lookBackDays,
  limit,
  offset,
});
/** Feed type and pagination for getSchedules and getScheduleTemplates. */
export const feedTypePageInputSchema = z.object({
  feedType: nonempty.describe('Feed type; schedules exist only for LMS_ORDER_REPORT'),
  limit,
  offset,
});

/** Body of createOrderTask. */
export const createOrderTaskInputSchema = z.object({
  task: z
    .object({
      feedType: nonempty.describe('LMS_ORDER_REPORT (the only supported value)'),
      schemaVersion: nonempty.describe(
        'LMS OrderReport schema version: an odd number of at least 1113, shown on the OrderReport reference page',
      ),
      filterCriteria: z
        .object({
          creationDateRange: dateWindow
            .optional()
            .describe(
              'Order creation window of at most 10 days; eBay defaults to the last 10 days',
            ),
          orderStatus: nonempty
            .optional()
            .describe('OrderStatusEnum: ACTIVE or COMPLETED; both when omitted'),
        })
        .optional()
        .describe('Order filters (modified-date filters are not supported by eBay yet)'),
    })
    .describe('CreateOrderTaskRequest body'),
});
/** Body of createInventoryTask. */
export const createInventoryTaskInputSchema = z.object({
  task: z
    .object({
      feedType: nonempty.describe('LMS_ACTIVE_INVENTORY_REPORT (the only supported value)'),
      schemaVersion: nonempty.describe('Must be 1.0'),
      filterCriteria: z
        .object({
          listingFormat: nonempty
            .optional()
            .describe('ListingFormatEnum: AUCTION or FIXED_PRICE; all formats when omitted'),
        })
        .optional()
        .describe('Limits the ActiveInventoryReport to one listing format'),
    })
    .describe('CreateInventoryTaskRequest body'),
});
/** Body and headers of createTask. */
export const createFeedTaskInputSchema = z.object({
  task: z
    .object({
      feedType: nonempty.describe(
        'Upload or download feed type, e.g. LMS_ADD_FIXED_PRICE_ITEM, LMS_REVISE_INVENTORY_STATUS, LMS_ORDER_ACK, LMS_ORDER_REPORT or a Seller Hub feed type',
      ),
      schemaVersion: nonempty.describe(
        'Feed file schema version for the feed type, per the LMS or Seller Hub feed quick reference',
      ),
    })
    .describe('CreateTaskRequest body'),
  marketplaceId: nonempty
    .optional()
    .describe(
      'X-EBAY-C-MARKETPLACE-ID for the task, e.g. EBAY_US; defaults to EBAY_MARKETPLACE_ID',
    ),
  acceptLanguage: nonempty
    .optional()
    .describe('Accept-Language, e.g. fr-CA with EBAY_CA or fr-BE with EBAY_BE'),
});
/** Body and headers of createCustomerServiceMetricTask. */
export const createCustomerServiceMetricTaskInputSchema = z.object({
  task: z
    .object({
      feedType: nonempty.describe('CUSTOMER_SERVICE_METRICS_REPORT (the only supported value)'),
      schemaVersion: nonempty.describe('Must be 1.0'),
      filterCriteria: z
        .object({
          customerServiceMetricType: nonempty.describe(
            'CustomerServiceMetricTypeEnum: ITEM_NOT_AS_DESCRIBED or ITEM_NOT_RECEIVED',
          ),
          evaluationMarketplaceId: nonempty.describe('Evaluated marketplace, e.g. EBAY_US'),
          listingCategories: z
            .array(nonempty)
            .optional()
            .describe('L1 category IDs; narrows ITEM_NOT_AS_DESCRIBED reports'),
          shippingRegions: z
            .array(nonempty)
            .optional()
            .describe(
              'ShippingRegionTypeEnum values (domestic or international); narrows ITEM_NOT_RECEIVED reports',
            ),
        })
        .describe('Report criteria; only CURRENT evaluations are available'),
    })
    .describe('CreateServiceMetricsTaskRequest body'),
  acceptLanguage,
});
/** Body of createSchedule. */
export const createFeedScheduleInputSchema = z.object({
  schedule: z
    .object({
      feedType: nonempty.describe('Feed type of the template; currently only LMS_ORDER_REPORT'),
      scheduleTemplateId: nonempty.describe(
        'ACTIVE schedule template ID from ebay_get_feed_schedule_templates',
      ),
      ...scheduleFields,
    })
    .describe('CreateUserScheduleRequest body; include every field the template requires'),
});
/** Schedule ID and body of updateSchedule. */
export const updateFeedScheduleInputSchema = z.object({
  scheduleId,
  schedule: z
    .object(scheduleFields)
    .describe('UpdateUserScheduleRequest body; include every field the template requires'),
});
/** Task ID and local feed file for uploadFile. */
export const uploadFeedFileInputSchema = z.object({
  taskId,
  path: nonempty.describe(
    'Absolute path or media:// reference inside the media allowlist; .xml, .csv, .zip or .gz up to 15 MiB',
  ),
});
